services:
  wp-db:
    image: mysql:8.0
    container_name: wp-db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wpnet

  wp:
    image: wordpress:latest
    container_name: wp-app
    restart: unless-stopped
    depends_on:
      - wp-db
    ports:
      - "${WP_PORT}:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: wp-db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wpnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp-phpmyadmin
    restart: unless-stopped
    depends_on:
      - wp-db
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: wp-db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wpnet

volumes:
  db_data:

networks:
  wpnet:
